# Generated by Django 2.0.3 on 2018-03-19 18:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('medium_id', models.SmallIntegerField(choices=[(1, 'facebook'), (2, 'instagram'), (3, 'twitter'), (4, 'google'), (5, 'linkedin'), (6, 'pinterest'), (7, 'tumblr'), (8, 'pushbullet'), (9, 'telegram'), (10, 'viber'), (11, 'snapchat'), (12, 'periscope'), (13, 'whatsapp'), (14, 'slack'), (15, 'vk'), (16, 'ok'), (17, 'bitly')])),
                ('key', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('scope', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
