# Generated by Django 2.0.3 on 2018-04-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='app_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
