# Generated by Django 2.1 on 2018-09-14 14:56

from django.db import migrations
import smp_base_django.models.Medium
import utils.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_credentials', '0003_auto_20180426_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='medium',
            field=utils.django.models.EnumField(choices=[(smp_base_django.models.Medium(1), 'facebook'), (smp_base_django.models.Medium(2), 'instagram'), (smp_base_django.models.Medium(3), 'twitter'), (smp_base_django.models.Medium(4), 'google'), (smp_base_django.models.Medium(5), 'linkedin'), (smp_base_django.models.Medium(6), 'pinterest'), (smp_base_django.models.Medium(7), 'tumblr'), (smp_base_django.models.Medium(8), 'pushbullet'), (smp_base_django.models.Medium(9), 'telegram'), (smp_base_django.models.Medium(10), 'viber'), (smp_base_django.models.Medium(11), 'snapchat'), (smp_base_django.models.Medium(12), 'periscope'), (smp_base_django.models.Medium(13), 'whatsapp'), (smp_base_django.models.Medium(14), 'slack'), (smp_base_django.models.Medium(15), 'vk'), (smp_base_django.models.Medium(16), 'ok'), (smp_base_django.models.Medium(17), 'bitly')]),
        ),
    ]
